backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "pblic/assets/blog"
puublic_foler: "/assets/blog"
collections: 
    - name: "blog"
      label: "Blog"
      folder: "src/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Athor", name: "author", widget: "string" }
        - { label: "Date", name: "date", widget: "datetime" }
        - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
        - { label: "Featured Image", name: "image", widget: "image" }
        - { label: "Image caption", name: "imageAlt", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }